name: Deploy to beta environment

# Only activate on tag creation on the main branch with an X.Y.Z format (e.g. 2.0.0 new major version)
on:
  push:
    tags:
        - 'v[0-9]+.[0-9]+.[0-9]+' # Regex to match tags with a X.Y.Z format
    # For testing
    branches:
        - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build changelog for beta release
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create changelog folder for beta release
        if: steps.build_changelog.outcome == 'success'
        run: mkdir playwhatsnew

      - name: Write changelog for beta release
        uses: DamianReeves/write-file-action@master
        if: steps.build_changelog.outcome == 'success'
        with:
          path: playwhatsnew/whatsnew-en-US
          contents: ${{ steps.build_changelog.outputs.changelog }}

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Create android_keystore.jks
        run: |
          echo '${{ secrets.UPLOAD_KEYSTORE }}' | base64 -d > upload-keystore.jks
          echo '${{ secrets.KEY_PROPERTIES }}' | base64 -d > key.properties

      - name: Assemble Release Bundle
        run: |
          ./gradlew bundleRelease

      - name: Create service_account.json
        run: |
          cd app/build/outputs/bundle/release

      - name: Create service_account.json
        run: echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service_account.json

      - name: Deploy to Beta
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: service_account.json
          packageName: com.challenge.get
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: beta
          whatsNewDirectory: playwhatsnew
