name: Deploy to beta environment

# Only activate on tag creation on the main branch with an X.Y.Z format (e.g. 2.0.0 new major version)
on:
  push:
    tags:
        - 'v[0-9]+.[0-9]+.[0-9]+' # Regex to match tags with a X.Y.Z format

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Create android_keystore.jks
        run: echo '${{ secrets.UPLOAD_KEYSTORE }}' > android_keystore.jks

      - name: Build with Gradle
        run: ./gradlew build

      - name: Assemble Release Bundle
        run: |
          ./gradlew bundleRelease

      - name: Create service_account.json
        run: echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service_account.json

      - name: Deploy to Beta
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: service_account.json
          packageName: com.challenge.get
          releaseFile: app/build/outputs/bundle/release/app-release.aab
          track: beta
          whatsNewDirectory: distribution/
